install numpy

In [21]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


Task 1

Create a 1D NumPy array with numbers from 1 to 10

In [22]:
import numpy as np

array_1d = np.arange(1, 11)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10]


Create a 2D NumPy array (3x3) with random integers (0–9)

In [23]:
array_2d = np.random.randint(0, 10, size=(3, 3))
print(array_2d)

[[3 3 9]
 [6 9 1]
 [2 4 8]]


Task 2

Find sum, mean, maximum

In [24]:
array_sum = array_2d.sum()
array_mean = array_2d.mean()
array_max = array_2d.max()

print(array_sum)
print(array_mean)
print(array_max)

45
5.0
9


Multiply all elements by 2

In [25]:
array_multiplied = array_2d * 2
print(array_multiplied)

[[ 6  6 18]
 [12 18  2]
 [ 4  8 16]]


Replace all values greater than 5 with 0

In [26]:
array_replaced = array_2d.copy()
array_replaced[array_replaced > 5] = 0
print(array_replaced)

[[3 3 0]
 [0 0 1]
 [2 4 0]]
